version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    container_name: laravel-app

  nginx:
    image: nginx:alpine
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - app
    container_name: laravel-nginx

  mysql:
    image: mysql:8
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - mysql-data:/var/lib/mysql
    container_name: laravel-mysql

volumes:
  mysql-data:
